In [1]:
import nltk;
nltk.download('punkt');
nltk.download('stopwords');
nltk.download('wordnet');

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\KE\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KE\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\KE\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [2]:
import pandas as pd
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer


In [3]:
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [4]:
df = pd.read_csv('Keywords_dataset.csv', on_bad_lines='skip') # create a DataFrame 

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7048 entries, 0 to 7047
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   documents    7048 non-null   object
 1   labels       7048 non-null   int64 
 2   label_names  7048 non-null   object
dtypes: int64(1), object(2)
memory usage: 165.3+ KB


In [5]:
def remove_noise(text):
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'http\S+|www\S+', '', text)         # remove links
    return text;

In [6]:
def lower_case(text):
    return text.lower()

In [7]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [8]:
def tokenize_text(text):
    return word_tokenize(text);

In [9]:
def remove_stopwords(tokens):
    filters=[];
    for w in tokens:
        if w not in stop_words:
          filters.append(w);
    return filters;

In [10]:
def apply_stemm(tokens):
    stemms=[]
    for w in tokens:
        word_stemmer=stemmer.stem(w)
        stemms.append(word_stemmer)
    return stemms;

In [11]:
def apply_lemmite(tokens):
    lemmtes=[]
    for w in tokens:
        word_lemmite=lemmatizer.lemmatize(w)
        lemmtes.append(word_lemmite)
    return lemmtes;

In [12]:
def preprocess_text(text):
    if not isinstance(text, str):
        return " "
    
    text=remove_noise(text)
    text=lower_case(text)
    text=remove_punctuation(text)
    tokens=tokenize_text(text)
    tokens=remove_stopwords(tokens)
    tokens=apply_stemm(tokens)
    tokens=apply_lemmite(tokens)

    return " ".join(tokens)

In [13]:
df.isnull().count()

documents      7048
labels         7048
label_names    7048
dtype: int64

In [14]:
df['documents'] = df['documents'].astype(str)
df = df.dropna(subset=['documents'])

df['cleaned_dataset_project'] = df['documents'].apply(preprocess_text)


In [15]:
df['cleaned_dataset_project'].head(5)

0    littl confus model bonnevil heard le se lse ss...
1    im familiar format xface thingi see folk heade...
2                                              word ye
3    attack iraqi drive kuwait countri whose citize...
4    ive spent two solid month argu thing object mo...
Name: cleaned_dataset_project, dtype: object

In [16]:
df.to_csv("cleaned_dataset_project.csv", index=False, encoding='utf-8-sig') #savinf
print("done")

done


In [17]:
print(" Sample before and after preprocessing:\n")
for i in range(10):
    print("Original:", df['documents'][i])
    print("Cleaned :", df['cleaned_dataset_project'][i])
    print("-" * 80)

 Sample before and after preprocessing:

Original: I am a little confused on all of the models of the 88-89 bonnevilles. I have heard of the LE SE LSE SSE SSEI. Could someone tell me the differences are far as features or performance. I am also curious to know what the book value is for prefereably the 89 model. And how much less than book value can you usually get them for. In other words how much are they in demand this time of year. I have heard that the mid-spring early summer is the best time to buy.
Cleaned : littl confus model bonnevil heard le se lse sse ssei could someon tell differ far featur perform also curiou know book valu prefer model much less book valu usual get word much demand time year heard midspr earli summer best time buy
--------------------------------------------------------------------------------
Original: I'm not familiar at all with the format of these "X-Face:" thingies, but after seeing them in some folks' headers, I've *got* to *see* them (and maybe mak

In [18]:
import nltk
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer  # For converting text to numerical features (BoW)

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

def apply_BoW(texts):

    vectorizer = CountVectorizer(stop_words='english')
    
    vectorizer.fit(texts)
    
    x = vectorizer.transform(texts)
    
    columns = vectorizer.get_feature_names_out()
    
    table = pd.DataFrame(x.todense(), columns=columns, index=texts)
    
    print("Displaying first 3 rows of the Bag of Words table:\n")
    print(table.head(3))  
    
    return table

In [19]:
apply_BoW(df['cleaned_dataset_project'].astype(str).tolist()) #تنفيذ

Displaying first 3 rows of the Bag of Words table:

                                                    aa  aaa  aaaaa  \
littl confus model bonnevil heard le se lse sse...   0    0      0   
im familiar format xface thingi see folk header...   0    0      0   
word ye                                              0    0      0   

                                                    aaaaarrrrgh  aaaall  \
littl confus model bonnevil heard le se lse sse...            0       0   
im familiar format xface thingi see folk header...            0       0   
word ye                                                       0       0   

                                                    aaack  aaaggghhh  \
littl confus model bonnevil heard le se lse sse...      0          0   
im familiar format xface thingi see folk header...      0          0   
word ye                                                 0          0   

                                                    aaalhtpao  aaareadm  aac 

,aa,aaa,aaaaa,aaaaarrrrgh,aaaall,aaack,aaaggghhh,aaalhtpao,aaareadm,aac,...,zybnrreqyab,zyda,zydanpsnavymil,zygon,zymospoach,zyweavdwqaedbvz,zyxel,zz,zzi,ÿhook
littl confus model bonnevil heard le se lse sse ssei could someon tell differ far featur perform also curiou know book valu prefer model much less book valu usual get word much demand time year heard midspr earli summer best time buy,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
im familiar format xface thingi see folk header ive got see mayb make one ive got dpgview linux box display uncompress xface ive manag compil compfac im look cant seem find xface anyon news header could would plea send xface header know ill probabl get littl swamp handl hope,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
word ye,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
attack iraqi drive kuwait countri whose citizen close blood busi tie saudi citizen think u help iraqi would swallow saudi arabia least eastern oilfield muslim countri much anyth help liber kuwait protect saudi arabia inde mass citizen demonstr favor butcher saddam kill lotsa muslim kill rape loot rel rich muslim also thumb nose west would defend saudi arabia roll back iraqi invas charg saudi arabia think good idea govern offici religion de facto de jure human natur like ambiti piou alway one rise power mani peopl world countri citizen realli know leader realli devout slick oper make sound like guy angel ilyess clarinet post edit stuff follow friday new york time report group definit conserv even sheikh baz follow think hous saud rule countri conserv enough nyt report besid complain govern conserv enough assert approx shiit kingdom apost charg saudi islam law bring death penalti diplomat guy sheikh bin jibrin isnt ilyess call sever punish woman drove public back protest ban woman drive guy group said abdelhamoud altoweijri said woman fire job jail brand prostitut want see happen ilyess ive heard mani muslim say ban woman drive basi quran ahadith etc yet folk like ban want woman fals call prostitut id choos hero wise ilyess reflex ralli behind anyon hate anyon hate say woman allow work say tv radio immor kingdom hous saud neither least favorit govern earth think restrict religi polit reedom lot among thing think like replac go lot wors citizen countri think hous saud feel heat late last six month ive read step harass muttawain religi policenot govern western woman fulli veil someth stupid woman imo send wrong signal moral ive read theyv crack homebas exparti religi gather even post reward governmentown newspap offer money anyon turn group exparti dare worship home secret place govern grown even intoler tri take wind sail moreconserv opposit unislam thing theyr small tast would happen guy overthrow hous saud like theyr tri long run realli rach other gener westisevilzionistsrulehatewestoryouareapuppet crowd want ilyess,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
ive spent two solid month argu thing object moral system exist,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
henri read correctli may ask put blackbodi interstellar space disregard sun nearbi larg warm object termperatur reach thermal equilibrium ambient radiat field that case let point interstellar dust molecul provid mani instanc thing well nottoofar blackbodi mani differ observ includ ira cobe determin interstellar dust grain temperatur rang k k might look confer proceed interstellar process ed j hollenbach h thronson jr publish tri articl tielen et al seab black insid disk galaxi temperatur vari quit bit place place close nearest ob associ would guess outsid galaxi cours thing arent vari hope look,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
actual thought mac suppous restart day jim smyton smytonjedu,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
sent version post ago swallow void apolog anyon end receiv oh wasnt confus understood person opinion thought discus need shorten game argument declar

In [20]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

df = pd.read_csv("cleaned_dataset_project.csv")

texts = df['documents'].fillna("")

vectorizer = TfidfVectorizer(stop_words='english')

X = vectorizer.fit_transform(texts)

columns = vectorizer.get_feature_names_out()

tfidf_df = pd.DataFrame(X.toarray(), columns=columns, index=texts)

print(tfidf_df.head())


                                                     00       000  0000  \
documents                                                                 
I am a little confused on all of the models of ...  0.0  0.000000   0.0   
I'm not familiar at all with the format of thes...  0.0  0.000000   0.0   
In a word, yes.                                     0.0  0.000000   0.0   
They were attacking the Iraqis to drive them ou...  0.0  0.031116   0.0   
I've just spent two solid months arguing that n...  0.0  0.000000   0.0   

                                                    00000  0001  00041555  \
documents                                                                   
I am a little confused on all of the models of ...    0.0   0.0       0.0   
I'm not familiar at all with the format of thes...    0.0   0.0       0.0   
In a word, yes.                                       0.0   0.0       0.0   
They were attacking the Iraqis to drive them ou...    0.0   0.0       0.0   
I've just sp

In [21]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import joblib


In [22]:
X_text = df['documents'].astype(str)   # النصوص
y = df['label_names']                  # التصنيف


In [23]:
X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text, y, test_size=0.2, random_state=42
)


In [24]:
vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

X_train = vectorizer.fit_transform(X_train_text)
X_test = vectorizer.transform(X_test_text)


In [25]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [26]:
y_pred = model.predict(X_test)


In [27]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Accuracy: 0.6964539007092199

Classification Report:
                          precision    recall  f1-score   support

             alt.atheism       0.49      0.44      0.46        52
           comp.graphics       0.56      0.71      0.63        62
 comp.os.ms-windows.misc       0.74      0.66      0.70        73
comp.sys.ibm.pc.hardware       0.62      0.56      0.59        73
   comp.sys.mac.hardware       0.74      0.70      0.72        74
          comp.windows.x       0.80      0.82      0.81        79
            misc.forsale       0.77      0.81      0.79        83
               rec.autos       0.66      0.79      0.72        57
         rec.motorcycles       0.65      0.71      0.68        83
      rec.sport.baseball       0.86      0.75      0.81        85
        rec.sport.hockey       0.83      0.93      0.88        80
               sci.crypt       0.91      0.71      0.80        75
         sci.electronics       0.46      0.63      0.53        62
                 sci.m

In [28]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)


Confusion Matrix:
 [[23  3  0  0  0  0  0  0  4  1  0  0  1  1  4 10  2  2  0  1]
 [ 0 44  2  2  2  5  1  0  0  1  1  0  3  0  1  0  0  0  0  0]
 [ 0  5 48  5  2  3  3  1  2  0  0  0  2  0  1  0  0  1  0  0]
 [ 0  4  9 41  2  3  2  0  1  1  0  1  7  2  0  0  0  0  0  0]
 [ 0  2  0  9 52  0  3  0  1  0  0  0  6  1  0  0  0  0  0  0]
 [ 0  6  4  0  0 65  0  0  1  0  0  0  1  1  1  0  0  0  0  0]
 [ 0  0  0  7  2  0 67  4  1  0  0  0  1  0  1  0  0  0  0  0]
 [ 1  0  0  0  1  0  2 45  3  0  1  0  2  0  0  1  1  0  0  0]
 [ 0  1  1  0  0  1  1  8 59  0  1  0  1  3  0  2  3  1  1  0]
 [ 2  0  0  0  0  0  0  1  2 64 12  0  1  0  1  0  1  1  0  0]
 [ 0  0  0  0  1  0  0  0  0  2 74  0  1  2  0  0  0  0  0  0]
 [ 1  3  0  0  3  2  0  0  2  0  0 53  3  1  1  0  4  1  1  0]
 [ 0  4  0  1  3  0  3  3  1  1  0  2 39  3  2  0  0  0  0  0]
 [ 1  0  0  0  1  0  2  2  0  0  0  0  7 57  2  0  0  1  1  0]
 [ 2  1  0  0  1  0  0  1  0  2  0  0  3  5 45  1  0  0  0  0]
 [ 5  1  0  0  0  0  0  0  0  0  0  

In [29]:
joblib.dump(model, "logistic_text_model.joblib")
joblib.dump(vectorizer, "tfidf_vectorizer.joblib")

print("Model and Vectorizer saved successfully!")


Model and Vectorizer saved successfully!


In [30]:
loaded_model = joblib.load("logistic_text_model.joblib")
loaded_vectorizer = joblib.load("tfidf_vectorizer.joblib")


In [31]:
new_text = ["machine learning improves data analysis"]

new_text_tfidf = loaded_vectorizer.transform(new_text)

prediction = loaded_model.predict(new_text_tfidf)
proba = loaded_model.predict_proba(new_text_tfidf)

print("Predicted Label:", prediction[0])
print("Prediction Probability:", proba)


Predicted Label: comp.graphics
Prediction Probability: [[0.03872052 0.07715114 0.05472409 0.07048433 0.06870329 0.06404882
  0.0489943  0.0491304  0.04434514 0.03664975 0.03089212 0.05336107
  0.07174312 0.05831344 0.06549424 0.0283445  0.03267509 0.03069015
  0.05173861 0.02379588]]
